### ISSUE TITLE
Vagrant login detail for debian-jessie64

### ISSUE THREAD

**Issue by vionemc** [paulproteus/ampache-sandstorm-prototype#13]
@paulproteus when I try to start vagrant, I got an error requiring login detail. Can you provide me with one?

More detail:

```
D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype>vagrant-spk vm up
Calling 'vagrant' 'up' in D:\xampp\htdocs\PHP projects\Asheesh Laroia\ampache-sandstorm-prototype\.sandstorm
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'sandstorm/debian-jessie64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'sandstorm/debian-jessie64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/sandstorm/debian-jessie64"]
Error:
Traceback (most recent call last):
  File "<string>", line 1022, in <module>
  File "<string>", line 1019, in main
  File "<string>", line 925, in vm_subcommand
  File "<string>", line 288, in call_vagrant_command
  File "subprocess.py", line 540, in check_call
subprocess.CalledProcessError: Command '['vagrant', 'up']' returned non-zero exit status 1
vagrant-spk returned -1
```

**Comment by paulproteus** [comment]
Hi @vionemc !

It looks to me like vagrant can't access the Internet on your computer. I say that because the URL works OK for me.

Per http://superuser.com/questions/804214/how-to-enable-vagrants-verbose-mode , can you add the `VAGRANT_LOG=info` environment variable, and maybe that will provide more info about why it's failing?

**Comment by vionemc** [comment]
Yup, it says the same. It's because I am not logged in yet (and maybe you already are now). And I need the username and password. Did you do `vagrant login` before?
And I can open the URL in my browser just fine.

```
 INFO interface: error: The box 'sandstorm/debian-jessie64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:
```

**Comment by paulproteus** [comment]
I haven't run `vagrant login` on this machine where I'm testing. I think it's not necessary.

You can try it if you want, though! You can create a free account on https://atlas.hashicorp.com/account/new and use that to log into Vagrant.

I'd like to generally test Vagrant's ability to reach the Internet for public resources by having you go through this tutorial -- https://www.vagrantup.com/docs/getting-started/ -- which uses Vagrant boxes that are definitely public. My hunch is that you'll find you can't access the boxes that are definitely public, in which case we'll know something is weird about your machine's Vagrant connectivity.

**Comment by paulproteus** [comment]
It could also have been a transient error. I wonder if you retry, does the problem go away? :)

**Comment by vionemc** [comment]
Hmmm, OK, thanks! That's very helpful. 
Nope, it does not go away. I am suspicious there is something wrong with my VirtualBox installation.

**Comment by paulproteus** [comment]
For what it's worth, the error is coming from Vagrant, not VirtualBox, from what I can tell.

Are you using Internet connectivity that uses a proxy? If so, we'll need to tell Vagrant about it probably.

If your Internet connection is proxying HTTPS traffic and changing certificates, then vagrant will probably have to get told about that, too, though I'm not sure how to.

**Comment by vionemc** [comment]
Nope, I don't use any proxy. I'll try to Google it. Maybe I'll find something

**Comment by paulproteus** [comment]
On my system, Vagrant seems to use `curl` to download things.

Also, you can run:

```
cd .sandstorm
vagrant up --debug
```

and get a _lot_ of debug output. Some of that will provide hints about the connectivity problem, I think. Feel free to share it in a gist or in a comment on this issue.

**Comment by paulproteus** [comment]
Looks like you're running into https://github.com/mitchellh/vagrant/issues/6754 and need a DLL!

**Comment by paulproteus** [comment]
Once you install https://www.microsoft.com/en-us/download/details.aspx?id=8328 , it should be fixed.

**Comment by paulproteus** [comment]
If this managed to resolve your question, please mark this as closed! Hopefully my research was helpful; if not, then we should make sure to get your problem resolved!

**Comment by vionemc** [comment]
Perfect! It solved it easily.
