### ISSUE TITLE
Import database dump or create a new one

### ISSUE THREAD

**Issue by vionemc** [paulproteus/ampache-sandstorm-prototype#14]
I see the database config in the config file, but I am curious whether you already have a database that I can just import or is there no database at all and I should make a fresh new one.

![foto-layar_080516_090806_pm](https://cloud.githubusercontent.com/assets/6565672/17439130/b5a6baa0-5b50-11e6-81d4-30699e3c8c65.jpg)

**Comment by vionemc** [comment]
I found a lot of dumps in the end. But I am not sure which one should I use.

![layar_penuh_080516_091045_pm](https://cloud.githubusercontent.com/assets/6565672/17439203/1494b81e-5b51-11e6-850e-d2196c12549f.jpg)

**Comment by paulproteus** [comment]
For database connectivity, see https://docs.sandstorm.io/en/latest/vagrant-spk/services/#mysql

In particular, you will need to create a database. If the Ampache install wizard doesn't let you create a database, see the note in the docs file above about adding a line to `.sandstorm/build.sh` to create a database.

For filling the database with data, my suggestion is to allow the Ampache wizard to create a fresh one.

**Comment by vionemc** [comment]
OK! Just imported the dump in `/sql/ampache.sql`, but I guess I should make a new one.

**Comment by paulproteus** [comment]
If your way works, I think that's fine too!

For what it's worth, in my opinion, having the database set up properly is out of scope for issue #1 -- it's relevant for #2 though. Therefore, for the pull request for issue #1 , I am 100% OK with whatever in terms of database setup.

This issue does seem in scope for #2 , and if your way works, then great, fine with me! :)
