### ISSUE TITLE
How much should I ask here?

### ISSUE THREAD

**Issue by vionemc** [paulproteus/ampache-sandstorm-prototype#16]
@paulproteus, do you prefer me to ask a lot in Github so people can learn from my experience, or do you prefer I ask just moderately? It seems you are interested more in contributing to the community than meeting a target.

**Comment by paulproteus** [comment]
Here is fine with me, if it works for you!

**Comment by paulproteus** [comment]
My goal is that yes, we should produce useful software. I'm also very happy to see the process for that documented publicly. So my priority is:
1. Working Ampache package
2. Useful contributions to the community as a whole

I'm perfectly OK with the process taking longer etc. to achieve goal 2 as well.

I hope that helps explain what I'm thinking!

**Comment by vionemc** [comment]
OK, great! You are awesome!
